# Generated by Django 5.1.6 on 2025-04-21 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acheter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_product', models.CharField(max_length=100)),
                ('id_client', models.CharField(max_length=10)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('categorie', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=500)),
                ('best_bider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tp.client')),
                ('biders', models.ManyToManyField(related_name='bids', to='tp.client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('categorie', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='tp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.sellproduct')),
            ],
        ),
    ]
