# Generated by Django 5.1.6 on 2025-02-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
