# Generated by Django 5.1.6 on 2025-04-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='best_bider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_auctions', to='tp.client'),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_products', to='tp.seller'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_products', to='tp.seller'),
        ),
        migrations.CreateModel(
            name='AuctionPanierItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_panier', to='tp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.auctionproduct')),
            ],
        ),
    ]
