# Generated by Django 5.1.6 on 2025-04-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0003_alter_auctionproduct_best_bider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_products', to='tp.seller'),
        ),
    ]
