# Generated by Django 5.1.6 on 2025-02-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
