# Generated by Django 5.1.6 on 2025-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
