# Generated by Django 5.1.6 on 2025-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0004_alter_auctionproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
