# Generated by Django 5.1.6 on 2025-04-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_auctionproduct_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionproduct',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sellproduct',
            old_name='categorie',
            new_name='category',
        ),
    ]
