# Generated by Django 5.1.6 on 2025-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0005_product_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='acheter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_product', models.CharField(max_length=100)),
                ('id_client', models.CharField(max_length=10)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
