# Generated by Django 5.1.6 on 2025-04-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0006_rename_categorie_auctionproduct_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='quantite',
            new_name='quantity',
        ),
    ]
