# Generated by Django 5.1.6 on 2025-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0006_acheter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
