# Generated by Django 5.1.6 on 2025-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='client', max_length=50),
            preserve_default=False,
        ),
    ]
