# Generated by Django 5.1.6 on 2025-03-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0009_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
