# Generated by Django 5.1.6 on 2025-03-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0010_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
