# Generated by Django 5.1.6 on 2025-03-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0012_rename_user_name_client_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='tp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.product')),
            ],
        ),
    ]
