# Generated by Django 5.1.6 on 2025-03-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0013_panieritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantite',
        ),
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.client')),
            ],
            bases=('tp.product',),
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tp.product')),
                ('quantite', models.IntegerField()),
            ],
            bases=('tp.product',),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.sellproduct'),
        ),
    ]
