# Generated by Django 5.1.6 on 2025-03-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0014_remove_product_quantite_auctionproduct_sellproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tp.client'),
        ),
    ]
