# Generated by Django 5.1.6 on 2025-03-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0015_alter_auctionproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tp.client'),
        ),
    ]
