# Generated by Django 5.1.6 on 2025-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0016_alter_auctionproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionproduct',
            old_name='user',
            new_name='best_bider',
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='biders',
            field=models.ManyToManyField(related_name='bids', to='tp.client'),
        ),
    ]
